Repository DevSquad10/b2b-service-platform, pull requests merged in 2025-04, with the labels that each got.

#179 # 176 Company 주석 추가 및 코드 문서화 개선
  com.devsquad10.company/src/main/java/com/devsquad10/company/application/service/CompanyEventService.java
  com.devsquad10.company/src/main/java/com/devsquad10/company/application/service/CompanyService.java
Labels: documentation

#180 #177 Product 주석 추가 및 코드 문서화 개선
  com.devsquad10.product/src/main/java/com/devsquad10/product/application/service/ProductEventService.java
  com.devsquad10.product/src/main/java/com/devsquad10/product/application/service/ProductMessageServiceImpl.java
  com.devsquad10.product/src/main/java/com/devsquad10/product/application/service/ProductService.java
Labels: documentation

#181 #178 Order 주석 추가 및 코드 문서화 개선
  com.devsquad10.order/src/main/java/com/devsquad10/order/application/service/OrderEventService.java
  com.devsquad10.order/src/main/java/com/devsquad10/order/application/service/OrderMessageServiceImpl.java
  com.devsquad10.order/src/main/java/com/devsquad10/order/application/service/OrderService.java
Labels: documentation

#174 #173 배송 관련 swagger 문서화
  com.devsquad10.gateway/src/main/java/com/devsquad10/gateway/infrastructure/filter/LocalJwtAuthenticationFilter.java
  com.devsquad10.shipping/build.gradle
  com.devsquad10.shipping/src/main/generated/com/devsquad10/shipping/domain/model/QShipping.java
  com.devsquad10.shipping/src/main/generated/com/devsquad10/shipping/domain/model/QShippingAgent.java
  com.devsquad10.shipping/src/main/generated/com/devsquad10/shipping/domain/model/QShippingHistory.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/dto/request/ShippingAgentSearchReqDto.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/dto/request/ShippingSearchReqDto.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/dto/request/ShippingUpdateReqDto.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/service/ShippingAgentService.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/service/ShippingService.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/domain/model/Shipping.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/domain/model/ShippingAgent.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/domain/model/ShippingHistory.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/config/swagger/SwaggerConfig.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/presentation/controller/ShippingAgentController.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/presentation/controller/ShippingController.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/presentation/swagger/ShippingAgentSwaggerDocs.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/presentation/swagger/ShippingSwaggerDocs.java
Labels: documentation, enhancement

#182 #165 Hub 도메인 API 테스트를 통한 Swagger 문서 자동화
  com.devsquad10.gateway/build.gradle
  com.devsquad10.gateway/src/main/java/com/devsquad10/gateway/infrastructure/filter/LocalJwtAuthenticationFilter.java
  com.devsquad10.hub/build.gradle
  com.devsquad10.hub/src/main/java/com/devsquad10/hub/presentation/controller/HubController.java
  com.devsquad10.hub/src/main/java/com/devsquad10/hub/presentation/controller/HubRouteController.java
  com.devsquad10.hub/src/main/java/com/devsquad10/hub/presentation/documentation/HubRouterSwaggerDocs.java
  com.devsquad10.hub/src/main/java/com/devsquad10/hub/presentation/documentation/HubSwaggerDocs.java
  com.devsquad10.hub/src/test/java/com/devsquad10/hub/HubApiDocsTest.java
  com.devsquad10.hub/src/test/java/com/devsquad10/hub/HubIntegrationTest.java
  com.devsquad10.hub/src/test/java/com/devsquad10/hub/HubRouteIntegrationTest.java
Labels: documentation, enhancement

#183 #141 AI 연동한 배송담당자 슬랙 메시지 발송 수정 및 docker 환경에 맞게 feign client URL 변경
  com.devsquad10.message/src/main/java/com/devsquad10/message/application/service/AiService.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/application/service/ShippingService.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/CompanyClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/HubClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/HubRouteClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/MessageClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/OrderClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/UserClient.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/dto/ShippingAgentFeignClientPatchRequest.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/client/dto/ShippingAgentFeignClientPostRequest.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/infrastructure/config/scheduling/SendSlackMessageScheduler.java
  com.devsquad10.shipping/src/main/java/com/devsquad10/shipping/presentation/controller/ShippingController.java
  com.devsquad10.shipping/src/test/java/com/devsquad10/shipping/ShippingAgentServiceIntegrationTest.java
Labels: bug, enhancement
